version: '3.8'

services:
  # 1. Cơ sở dữ liệu nguồn PostgreSQL (chứa dữ liệu giao dịch Toy Store)
  postgres-source:
    image: postgres:15-alpine
    container_name: postgres_source_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nguyen
      - POSTGRES_DB=toy_store_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  # 2. Apache Airflow (Bộ điều phối & xử lý ETL Pipeline)
  airflow-app:
    build: .
    container_name: airflow_app_container
    ports:
      - "8080:8080"
    environment:
      # Biến kết nối tới PostgreSQL (Lưu ý: DB_HOST dùng tên service 'postgres-source')
      - DB_USER=postgres
      - DB_PASSWORD=nguyen
      - DB_HOST=postgres-source
      - DB_PORT=5432
      - DB_NAME=toy_store_db
      # Thiết lập thư mục chứa các DAGs của Airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/app/dags
      # Cho phép nạp DAG mẫu của Airflow hay không (False để giữ giao diện sạch)
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # AWS/MinIO configuration
      - AWS_ACCESS_KEY_ID=minio_admin
      - AWS_SECRET_ACCESS_KEY=minio_password
      - AWS_ENDPOINT_URL=http://minio:9000
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      # Gắn kết (Mount) các thư mục code cục bộ vào container để tiện phát triển
      - ./dags:/app/dags
      - ./etls:/app/etls
      - ./utils:/app/utils
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tests:/app/tests
    depends_on:
      - postgres-source
      - minio
    restart: always

  # 3. Metabase (Trực quan hóa dữ liệu và xây dựng Dashboard)
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_container
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - postgres-source
    restart: always

  # 4. MinIO Object Storage (Lưu trữ file Parquet Data Lakehouse)
  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  # 5. Tự động khởi tạo bucket cho MinIO
  minio-create-buckets:
    image: minio/mc
    container_name: minio_bucket_creator
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 minio_admin minio_password; do echo 'Waiting for MinIO...'; sleep 1; done;
      /usr/bin/mc mb --ignore-existing myminio/toy-store-lakehouse;
      exit 0;
      "

volumes:
  pg_data:
  metabase_data:
  minio_data:
